
trigger:
- master

# Variables
variables:
  tag: '$(Build.BuildId)'

stages:
# Build Stage 
- stage: Build
  displayName: Build pannanum
  jobs:
  - job: Build
    displayName: Build pannitiya
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
 
    - task: Docker@2
      inputs:
        containerRegistry: 'azuredevopssri'
        repository: 'custom2aksnginxapp1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(Build.SourceVersion)